export const CHANGE_PAGE_REQUEST = 'CHANGE_PAGE_REQUEST'
export const CHANGE_PAGE_SUCCESS = 'CHANGE_PAGE_SUCCESS'
export const CHANGE_PAGE_FAIL = 'CHANGE_PAGE_FAIL'
export const CHANGE_PAGE = 'CHANGE_PAGE'

